grpc:
  server:
    network: tcp
    host: localhost
    port: 50051
db:
  postgres:
    driver: postgres
    host: localhost
    port: 5432
    name: scribble
    user: scribble
    password: scribble
    sslMode: disable
