http:
  host: localhost
  port: 5001
grpc:
  notebook:
    host: localhost
    port: 50050
db:
  postgres:
    driver: postgres
    host: localhost
    port: 5432
    name: scribble
    user: scribble
    password: scribble
    sslMode: disable
