grpc:
  server:
    network: tcp
    host: 0.0.0.0
    port: 50050
db:
  postgres:
    driver: postgres
    host: postgres
    port: 5432
    name: scribble
    user: postgres
    password: postgres
    sslMode: disable
