grpc:
  network: tcp
  host: localhost
  port: 50051
storage:
  minio:
    accessKey: scribble
    secretKey: scribble123
    endpoint: localhost:9000
    bucket: scribble
    region: eu-west-1
    useSSL: false
