name: scribble-dev

services:
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: scribble
      POSTGRES_USER: scribble
      POSTGRES_PASSWORD: scribble
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: scribble
      MINIO_ROOT_PASSWORD: scribble123
      MINIO_BROWSER: "on"
      MINIO_REGION: eu-west-1
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001

volumes:
  postgres_data:
  minio_data:
