grpc:
  server:
    network: tcp
    host: 0.0.0.0
    port: 50052
db:
  postgres:
    driver: postgres
    host: postgres
    port: 5432
    name: scribble
    user: postgres
    password: postgres
    sslMode: disable
storage:
  minio:
    accessKey: minio
    secretKey: minio123
    endpoint: minio:9000
    bucket: scribble
    region: eu-west-1
    useSSL: false
