grpc:
  server:
    network: tcp
    address: 0.0.0.0:50053
db:
  postgres:
    url: postgres://postgres:postgres@postgres:5432/scribble?sslmode=disable
storage:
  minio:
    accessKey: minio
    secretKey: minio123
    endpoint: minio:9000
    bucket: scribble
    region: eu-west-1
    useSSL: false
