extend type Mutation {
    login(input: LoginInput!): AuthOutput!
    register(input: RegisterInput!): AuthOutput!
}

type AuthOutput {
    token: String!
}

input LoginInput {
    email: String!
    password: String!
}

input RegisterInput {
    email: String!
    firstName: String
    lastName: String
    password: String!
}
