extend type Mutation {
    downloadFile(id: UUID!, noteID: UUID!): Boolean!
    removeFile(id: UUID!, noteID: UUID!): Boolean!
}

type File {
    id: UUID!
    name: String!
    size: Int64!
    contentType: String!
    createdAt: Time!
}

type DownloadedFile {
    name: String!
    size: Int64!
}
