extend type Mutation {
    uploadFile(noteID: UUID!, file: Upload!): Boolean!
    removeFile(id: UUID!, noteID: UUID!): Boolean!
}

type File {
    id: UUID!
    name: String!
    size: Int64!
    contentType: String!
    createdAt: Time!
}
