extend type Mutation {
    uploadFile(noteID: UUID!, file: Upload!): Boolean! @isAuthenticated
    removeFile(id: UUID!, noteID: UUID!): Boolean! @isAuthenticated
}

type File {
    id: UUID!
    name: String!
    size: Int64!
    contentType: String!
    createdAt: Time!
}
