extend type Query {
    note(id: UUID!, notebookID: UUID!): Note! @isAuthenticated
    notes(notebookID: UUID!): [Note]! @isAuthenticated
}

extend type Mutation {
    createNote(notebookID: UUID!, input: CreateNoteInput!): Boolean! @isAuthenticated
    updateNote(id: UUID!, notebookID: UUID!, input: UpdateNoteInput!): Boolean! @isAuthenticated
    deleteNote(id: UUID!, notebookID: UUID!): Boolean! @isAuthenticated
}

type Note {
    id: UUID!
    title: String!
    content: String
    files: [File]! @goField(forceResolver: true)
    createdAt: Time!
}

input CreateNoteInput {
    title: String!
    content: String
    files: [Upload]
}

input UpdateNoteInput {
    title: String
    content: String
}
