extend type Query {
    note(id: UUID!, notebookID: UUID!): Note!
    notes(notebookID: UUID!): [Note]!
}

extend type Mutation {
    createNote(notebookID: UUID!, input: CreateNoteInput!): Boolean!
    updateNote(id: UUID!, notebookID: UUID!, input: UpdateNoteInput!): Boolean!
    deleteNote(id: UUID!, notebookID: UUID!): Boolean!
}

type Note {
    id: UUID!
    title: String!
    body: String!
    createdAt: Time!
    files: [File]!
}

input CreateNoteInput {
    title: String!
    body: String!
    files: [Upload]!
}

input UpdateNoteInput {
    title: String!
    body: String!
}
