extend type Query {
    notebooks: [Notebook]! @isAuthenticated
}

extend type Mutation {
    createNotebook(input: CreateNotebookInput!): Boolean! @isAuthenticated
    updateNotebook(id: UUID!, input: UpdateNotebookInput!): Boolean! @isAuthenticated
    deleteNotebook(id: UUID!): Boolean! @isAuthenticated
}

type Notebook {
    id: UUID!
    title: String!
    description: String
    createdAt: Time!
}

input CreateNotebookInput {
    title: String!
    description: String
}

input UpdateNotebookInput {
    title: String
    description: String
}
