http:
  host: localhost
  port: 5001
grpc:
  notebook:
    host: localhost
    port: 50050
  storage:
    host: localhost
    port: 50051
  file:
    host: localhost
    port: 50052
db:
  postgres:
    driver: postgres
    host: localhost
    port: 5432
    name: scribble
    user: scribble
    password: scribble
    sslMode: disable
