package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/google/uuid"
)

// DownloadFile is the resolver for the downloadFile field.
func (r *mutationResolver) DownloadFile(ctx context.Context, id uuid.UUID, noteID uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DownloadFile - downloadFile"))
}

// RemoveFile is the resolver for the removeFile field.
func (r *mutationResolver) RemoveFile(ctx context.Context, id uuid.UUID, noteID uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: RemoveFile - removeFile"))
}
