package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/google/uuid"
	"github.com/yahn1ukov/scribble/apps/gateway/internal/gql/gqlmodels"
	"github.com/yahn1ukov/scribble/libs/grpc"
	notebookpb "github.com/yahn1ukov/scribble/proto/notebook"
)

func (r *mutationResolver) CreateNotebook(ctx context.Context, input gqlmodels.CreateNotebookInput) (bool, error) {
	userID := r.middleware.GetUserIDFromCtx(ctx)

	if _, err := r.notebookClient.CreateNotebook(
		ctx,
		&notebookpb.CreateNotebookRequest{
			UserId:      userID,
			Title:       input.Title,
			Description: input.Description,
		},
	); err != nil {
		return false, grpc.ParseError(err).Error()
	}

	return true, nil
}

func (r *mutationResolver) UpdateNotebook(ctx context.Context, id uuid.UUID, input gqlmodels.UpdateNotebookInput) (bool, error) {
	userID := r.middleware.GetUserIDFromCtx(ctx)

	if _, err := r.notebookClient.UpdateNotebook(
		ctx,
		&notebookpb.UpdateNotebookRequest{
			Id:          id.String(),
			UserId:      userID,
			Title:       input.Title,
			Description: input.Description,
		},
	); err != nil {
		return false, grpc.ParseError(err).Error()
	}

	return true, nil
}

func (r *mutationResolver) DeleteNotebook(ctx context.Context, id uuid.UUID) (bool, error) {
	userID := r.middleware.GetUserIDFromCtx(ctx)

	if _, err := r.notebookClient.DeleteNotebook(
		ctx,
		&notebookpb.DeleteNotebookRequest{
			Id:     id.String(),
			UserId: userID,
		},
	); err != nil {
		return false, grpc.ParseError(err).Error()
	}

	return true, nil
}

func (r *queryResolver) Notebooks(ctx context.Context) ([]*gqlmodels.Notebook, error) {
	userID := r.middleware.GetUserIDFromCtx(ctx)

	res, err := r.notebookClient.ListNotebooks(
		ctx,
		&notebookpb.ListNotebooksRequest{
			UserId: userID,
		},
	)
	if err != nil {
		return nil, grpc.ParseError(err).Error()
	}

	var output []*gqlmodels.Notebook
	for _, notebook := range res.Notebooks {
		output = append(
			output,
			&gqlmodels.Notebook{
				ID:          uuid.MustParse(notebook.Id),
				Title:       notebook.Title,
				Description: notebook.Description,
				CreatedAt:   notebook.CreatedAt.AsTime(),
			},
		)
	}

	return output, nil
}
