http:
  host: localhost
  port: 8000
grpc:
  client:
    notebook:
      host: localhost
      port: 50050
    note:
      host: localhost
      port: 50051
    file:
      host: localhost
      port: 50052
