http:
  address: 0.0.0.0:8000
grpc:
  client:
    user:
      address: user:50050
    notebook:
      address: notebook:50051
    note:
      address: note:50052
    file:
      address: file:50053
    auth:
      address: auth:50054
jwt:
  secret: asfsf90s8f0s8f0sd8fsfklsjfsdof8uqewrnmnaldf
