// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlmodels

import (
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/google/uuid"
)

type CreateNoteInput struct {
	Title string            `json:"title"`
	Body  string            `json:"body"`
	Files []*graphql.Upload `json:"files"`
}

type CreateNotebookInput struct {
	Title string `json:"title"`
}

type DownloadedFile struct {
	Name string `json:"name"`
	Size int64  `json:"size"`
}

type File struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Size        int64     `json:"size"`
	ContentType string    `json:"contentType"`
	CreatedAt   time.Time `json:"createdAt"`
}

type Mutation struct {
}

type Note struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	Body      string    `json:"body"`
	Files     []*File   `json:"files"`
	CreatedAt time.Time `json:"createdAt"`
}

type Notebook struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	CreatedAt time.Time `json:"createdAt"`
}

type Query struct {
}

type UpdateNoteInput struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}

type UpdateNotebookInput struct {
	Title string `json:"title"`
}
