grpc:
  network: tcp
  host: localhost
  port: 50051
db:
  postgres:
    driver: postgres
    host: localhost
    port: 5432
    name: scribble
    user: scribble
    password: scribble
    sslMode: disable
storage:
  minio:
    accessKey: scribble
    secretKey: scribble123
    endpoint: localhost:9000
    bucket: scribble
    region: eu-west-1
    useSSL: false
